#!/usr/bin/env python3
"""Generate tree-sitter grammar.js and highlight queries from Radix sources."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from radix_vocab import load_vocabulary

REPO_ROOT = Path(__file__).resolve().parents[1]
JS_GENERATED_HEADER = "// Generated by scripta/generate_grammar.py — do not edit by hand.\n"
SCM_GENERATED_HEADER = "; Generated by scripta/generate_grammar.py — do not edit by hand.\n"


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def js_keyword_rule(name: str, words: list[str]) -> str:
    if not words:
        return f"        {name}: $ => choice(),\n"
    parts = ",\n".join(f"                {js_string(word)}" for word in words)
    return f"        {name}: $ =>\n            choice(\n{parts},\n            ),\n\n"


def longest_first(words: list[str]) -> list[str]:
    return sorted(words, key=lambda s: (-len(s), s))


def js_operator_rule(operators: list[str]) -> str:
    ordered = longest_first(operators)
    parts = ",\n".join(f"                {js_string(op)}" for op in ordered)
    return (
        "        operator: $ =>\n"
        "            token(\n"
        "                choice(\n"
        f"{parts},\n"
        "                ),\n"
        "            ),\n\n"
    )


def annotation_argument_builtin_types(vocab: dict[str, list[str]]) -> list[str]:
    blocked = set(vocab["annotation_name"])
    return [name for name in vocab["builtin_type"] if name not in blocked]


def build_annotation_rules(vocab: dict[str, list[str]]) -> str:
    arg_types = annotation_argument_builtin_types(vocab)
    return (
        "        at_sign: ($) => '@',\n\n"
        "        lbrace: ($) => '{',\n\n"
        "        rbrace: ($) => '}',\n\n"
        "        eq_sign: ($) => '=',\n\n"
        "        comma_sign: ($) => ',',\n\n"
        "        annotation: ($) =>\n"
        "            prec(2, seq(\n"
        "                $.at_sign,\n"
        "                field('name', $.annotation_name),\n"
        "                optional(choice($.braced_annotation, $.annotation_arguments)),\n"
        "            )),\n\n"
        + js_keyword_rule("known_annotation_name", vocab["annotation_name"])
        + "        annotation_name: ($) =>\n"
        "            choice(\n"
        "                $.known_annotation_name,\n"
        "                $.identifier,\n"
        "            ),\n\n"
        + js_keyword_rule("annotation_modifier", vocab["annotation_modifier"])
        + js_keyword_rule("annotation_value_type", arg_types)
        + "        braced_annotation: ($) => seq(\n"
        "            $.lbrace,\n"
        "            optional(\n"
        "                seq(\n"
        "                    $.annotation_field,\n"
        "                    repeat(seq($.comma_sign, $.annotation_field)),\n"
        "                    optional($.comma_sign),\n"
        "                ),\n"
        "            ),\n"
        "            $.rbrace,\n"
        "        ),\n\n"
        "        annotation_field: ($) =>\n"
        "            seq(\n"
        "                field('key', choice($.annotation_modifier, $.identifier)),\n"
        "                $.eq_sign,\n"
        "                field(\n"
        "                    'value',\n"
        "                    choice(\n"
        "                        $.string,\n"
        "                        $.ascii_string,\n"
        "                        $.backtick_string,\n"
        "                        $.guillemet_string,\n"
        "                        $.octeti_string,\n"
        "                        $.identifier,\n"
        "                        $.annotation_value_type,\n"
        "                        $.number,\n"
        "                        $.boolean,\n"
        "                    ),\n"
        "                ),\n"
        "            ),\n\n"
        "        annotation_arguments: ($) => repeat1($._annotation_argument),\n\n"
        "        _annotation_argument: ($) =>\n"
        "            choice(\n"
        "                $.annotation_modifier,\n"
        "                $.string,\n"
        "                $.ascii_string,\n"
        "                $.backtick_string,\n"
        "                $.guillemet_string,\n"
        "                $.octeti_string,\n"
        "                $.keyword_declaration,\n"
        "                $.annotation_value_type,\n"
        "                $.keyword_other,\n"
        "                $.boolean,\n"
        "                $.identifier,\n"
        "                $.number,\n"
        "            ),\n\n"
    )


def build_grammar_js(vocab: dict[str, list[str]]) -> str:
    return (
        JS_GENERATED_HEADER
        + "// Faber tree-sitter grammar — token highlighting with annotation structure.\n"
        + "// Full structural parsing is intentionally out of scope.\n\n"
        + "module.exports = grammar({\n"
        + "    name: 'faber',\n\n"
        + "    externals: ($) => [$.line_comment, $.faber_newline],\n\n"
        + "    extras: ($) => [/[ \\t]+/],\n\n"
        + "    conflicts: ($) => [[$.annotation], [$.annotation_arguments]],\n\n"
        + "    rules: {\n"
        + "        program: ($) =>\n"
        "            seq(optional($.frontmatter), repeat(choice($.annotation, $._token))),\n\n"
        + "        frontmatter: ($) =>\n"
        + "            token(\n"
        + "                seq(\n"
        + "                    '+++',\n"
        + "                    /[^+]*?/,\n"
        + "                    '+++',\n"
        + "                    optional(/\\r?\\n/),\n"
        + "                ),\n"
        + "            ),\n\n"
        + build_annotation_rules(vocab)
        + "        _token: ($) =>\n"
        + "            choice(\n"
        + "                $.line_comment,\n"
        + "                $.faber_newline,\n"
        + "                $.keyword_control,\n"
        + "                $.keyword_declaration,\n"
        + "                $.keyword_other,\n"
        + "                $.builtin_type,\n"
        + "                $.boolean,\n"
        + "                $.guillemet_string,\n"
        + "                $.octeti_string,\n"
        + "                $.backtick_string,\n"
        + "                $.ascii_string,\n"
        + "                $.string,\n"
        + "                $.number,\n"
        + "                $.identifier,\n"
        + "                $.operator,\n"
        + "                $.punctuation,\n"
        + "                $.hash,\n"
        + "            ),\n\n"
        + js_keyword_rule("keyword_control", vocab["keyword_control"])
        + js_keyword_rule("keyword_declaration", vocab["keyword_declaration"])
        + js_keyword_rule("keyword_other", vocab["keyword_other"])
        + js_keyword_rule("builtin_type", vocab["builtin_type"])
        + js_keyword_rule("boolean", vocab["boolean"])
        + "        guillemet_string: ($) =>\n"
        + "            token(seq('«', /[^»]*/, '»')),\n\n"
        + "        octeti_string: ($) =>\n"
        + "            token(seq('|', /[^|]*/, '|')),\n\n"
        + "        backtick_string: ($) =>\n"
        + "            token(seq('`', /[^`]*/, '`')),\n\n"
        + "        ascii_string: ($) =>\n"
        + "            token(seq(\"'\", /([^'\\\\\\n]|\\\\.)*/, \"'\")),\n\n"
        + "        string: ($) =>\n"
        + "            token(seq('\"', /([^\"\\\\\\n]|\\\\.)*/, '\"')),\n\n"
        + "        number: ($) =>\n"
        + "            token(\n"
        + "                choice(\n"
        + "                    /0[xX][0-9A-Fa-f_]+/,\n"
        + "                    /0[bB][01_]+/,\n"
        + "                    /0[oO][0-7_]+/,\n"
        + "                    /\\d[\\d_]*(\\.\\d[\\d_]*)?([eE][+-]?\\d+)?/,\n"
        + "                ),\n"
        + "            ),\n\n"
        + "        identifier: ($) => /[A-Za-z_][A-Za-z0-9_]*/,\n\n"
        + js_operator_rule(vocab["operator"])
        + "        punctuation: ($) => choice('(', ')', '{', '}', '[', ']', ',', ':', ';'),\n\n"
        + "        hash: ($) => '#',\n"
        + "    },\n"
        + "});\n"
    )


def build_highlights_scm() -> str:
    return (
        SCM_GENERATED_HEADER
        + "; Faber syntax highlighting queries.\n\n"
        + "(frontmatter) @comment\n"
        + "(line_comment) @comment\n\n"
        + "(annotation) @attribute\n"
        + "(annotation\n"
        + "  (at_sign) @operator\n"
        + "  name: (annotation_name) @attribute)\n\n"
        + "(at_sign) @operator\n"
        + "(eq_sign) @operator\n"
        + "(comma_sign) @punctuation.delimiter\n"
        + "(lbrace) @punctuation.bracket\n"
        + "(rbrace) @punctuation.bracket\n\n"
        + "(annotation_name) @attribute\n"
        + "(known_annotation_name) @attribute\n\n"
        + "(annotation_modifier) @property\n\n"
        + "(annotation_field\n"
        + "  (annotation_modifier) @property\n"
        + "  (string) @string)\n\n"
        + "(annotation_arguments\n"
        + "  (annotation_modifier) @property\n"
        + "  (string) @string\n"
        + "  (ascii_string) @string\n"
        + "  (backtick_string) @string\n"
        + "  (guillemet_string) @string\n"
        + "  (octeti_string) @string\n"
        + "  (identifier) @variable\n"
        + "  (annotation_value_type) @type.builtin\n"
        + "  (keyword_declaration) @keyword\n"
        + "  (keyword_other) @keyword\n"
        + "  (boolean) @boolean\n"
        + "  (number) @number)\n\n"
        + "(keyword_control) @keyword\n"
        + "(keyword_declaration) @keyword\n"
        + "(keyword_other) @keyword\n"
        + "(builtin_type) @type.builtin\n"
        + "(boolean) @boolean\n"
        + "(guillemet_string) @string\n"
        + "(octeti_string) @string\n"
        + "(backtick_string) @string\n"
        + "(ascii_string) @string\n"
        + "(string) @string\n"
        + "(number) @number\n"
        + "(identifier) @variable\n"
        + "(operator) @operator\n"
        + "(punctuation) @punctuation.bracket\n"
        + "(hash) @operator\n"
    )


def write_outputs(vocab: dict[str, list[str]]) -> None:
    grammar = REPO_ROOT / "grammar.js"
    grammar.write_text(build_grammar_js(vocab), encoding="utf-8")

    highlights = build_highlights_scm()
    for path in (
        REPO_ROOT / "queries" / "highlights.scm",
        REPO_ROOT / "languages" / "faber" / "highlights.scm",
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(highlights, encoding="utf-8")

    manifest = REPO_ROOT / "scripta" / "vocabulary.json"
    manifest.write_text(json.dumps(vocab, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--radix-root",
        type=Path,
        default=None,
        help="path to radix repo (default: ../radix or $RADIX_ROOT)",
    )
    args = parser.parse_args()

    try:
        vocab = load_vocabulary(args.radix_root)
    except FileNotFoundError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1

    write_outputs(vocab)
    print("generated grammar.js, highlight queries, and scripta/vocabulary.json")
    for bucket, words in vocab.items():
        print(f"  {bucket}: {len(words)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
