#!/usr/bin/env python3
"""Generate tree-sitter grammar.js and highlight queries from Radix sources."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from radix_vocab import load_vocabulary

REPO_ROOT = Path(__file__).resolve().parents[1]
JS_GENERATED_HEADER = "// Generated by scripta/generate_grammar.py — do not edit by hand.\n"
SCM_GENERATED_HEADER = "; Generated by scripta/generate_grammar.py — do not edit by hand.\n"


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def js_keyword_rule(name: str, words: list[str]) -> str:
    if not words:
        return f"        {name}: $ => choice(),\n"
    parts = ",\n".join(f"                {js_string(word)}" for word in words)
    return f"        {name}: $ =>\n            choice(\n{parts},\n            ),\n\n"


def longest_first(words: list[str]) -> list[str]:
    return sorted(words, key=lambda s: (-len(s), s))


def js_operator_rule(operators: list[str]) -> str:
    ordered = longest_first(operators)
    parts = ",\n".join(f"                {js_string(op)}" for op in ordered)
    return (
        "        operator: $ =>\n"
        "            token(\n"
        "                choice(\n"
        f"{parts},\n"
        "                ),\n"
        "            ),\n\n"
    )


def build_grammar_js(vocab: dict[str, list[str]]) -> str:
    return (
        JS_GENERATED_HEADER
        + "// Faber tree-sitter grammar — token highlighting only.\n"
        + "// Structural parsing is intentionally out of scope.\n\n"
        + "module.exports = grammar({\n"
        + "    name: 'faber',\n\n"
        + "    externals: ($) => [$.line_comment, $.faber_newline],\n\n"
        + "    extras: ($) => [/[ \\t]+/],\n\n"
        + "    rules: {\n"
        + "        program: ($) => seq(optional($.frontmatter), repeat($._token)),\n\n"
        + "        frontmatter: ($) =>\n"
        + "            token(\n"
        + "                seq(\n"
        + "                    '+++',\n"
        + "                    /[^+]*?/,\n"
        + "                    '+++',\n"
        + "                    optional(/\\r?\\n/),\n"
        + "                ),\n"
        + "            ),\n\n"
        + "        _token: ($) =>\n"
        + "            choice(\n"
        + "                $.line_comment,\n"
        + "                $.faber_newline,\n"
        + "                $.keyword_control,\n"
        + "                $.keyword_declaration,\n"
        + "                $.keyword_other,\n"
        + "                $.builtin_type,\n"
        + "                $.boolean,\n"
        + "                $.guillemet_string,\n"
        + "                $.octeti_string,\n"
        + "                $.backtick_string,\n"
        + "                $.ascii_string,\n"
        + "                $.string,\n"
        + "                $.number,\n"
        + "                $.identifier,\n"
        + "                $.operator,\n"
        + "                $.punctuation,\n"
        + "                $.hash,\n"
        + "            ),\n\n"
        + js_keyword_rule("keyword_control", vocab["keyword_control"])
        + js_keyword_rule("keyword_declaration", vocab["keyword_declaration"])
        + js_keyword_rule("keyword_other", vocab["keyword_other"])
        + js_keyword_rule("builtin_type", vocab["builtin_type"])
        + js_keyword_rule("boolean", vocab["boolean"])
        + "        guillemet_string: ($) =>\n"
        + "            token(seq('«', /[^»]*/, '»')),\n\n"
        + "        octeti_string: ($) =>\n"
        + "            token(seq('|', /[^|]*/, '|')),\n\n"
        + "        backtick_string: ($) =>\n"
        + "            token(seq('`', /[^`]*/, '`')),\n\n"
        + "        ascii_string: ($) =>\n"
        + "            token(seq(\"'\", /([^'\\\\\\n]|\\\\.)*/, \"'\")),\n\n"
        + "        string: ($) =>\n"
        + "            token(seq('\"', /([^\"\\\\\\n]|\\\\.)*/, '\"')),\n\n"
        + "        number: ($) =>\n"
        + "            token(\n"
        + "                choice(\n"
        + "                    /0[xX][0-9A-Fa-f_]+/,\n"
        + "                    /0[bB][01_]+/,\n"
        + "                    /0[oO][0-7_]+/,\n"
        + "                    /\\d[\\d_]*(\\.\\d[\\d_]*)?([eE][+-]?\\d+)?/,\n"
        + "                ),\n"
        + "            ),\n\n"
        + "        identifier: ($) => /[A-Za-z_][A-Za-z0-9_]*/,\n\n"
        + js_operator_rule(vocab["operator"])
        + "        punctuation: ($) => choice('(', ')', '{', '}', '[', ']', ',', ':', ';'),\n\n"
        + "        hash: ($) => '#',\n"
        + "    },\n"
        + "});\n"
    )


def build_highlights_scm() -> str:
    return (
        SCM_GENERATED_HEADER
        + "; Faber syntax highlighting queries.\n\n"
        + "(frontmatter) @comment\n"
        + "(line_comment) @comment\n"
        + "(keyword_control) @keyword\n"
        + "(keyword_declaration) @keyword\n"
        + "(keyword_other) @keyword\n"
        + "(builtin_type) @type.builtin\n"
        + "(boolean) @boolean\n"
        + "(guillemet_string) @string\n"
        + "(octeti_string) @string\n"
        + "(backtick_string) @string\n"
        + "(ascii_string) @string\n"
        + "(string) @string\n"
        + "(number) @number\n"
        + "(identifier) @variable\n"
        + "(operator) @operator\n"
        + "(punctuation) @punctuation.bracket\n"
        + "(hash) @operator\n"
    )


def write_outputs(vocab: dict[str, list[str]]) -> None:
    grammar = REPO_ROOT / "grammar.js"
    grammar.write_text(build_grammar_js(vocab), encoding="utf-8")

    highlights = build_highlights_scm()
    for path in (
        REPO_ROOT / "queries" / "highlights.scm",
        REPO_ROOT / "languages" / "faber" / "highlights.scm",
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(highlights, encoding="utf-8")

    manifest = REPO_ROOT / "scripta" / "vocabulary.json"
    manifest.write_text(json.dumps(vocab, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--radix-root",
        type=Path,
        default=None,
        help="path to radix repo (default: ../radix or $RADIX_ROOT)",
    )
    args = parser.parse_args()

    try:
        vocab = load_vocabulary(args.radix_root)
    except FileNotFoundError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1

    write_outputs(vocab)
    print("generated grammar.js, highlight queries, and scripta/vocabulary.json")
    for bucket, words in vocab.items():
        print(f"  {bucket}: {len(words)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())