// Generated by scripta/generate_grammar.py — do not edit by hand.
; Faber syntax highlighting queries.

(frontmatter) @comment
(line_comment) @comment
(keyword_control) @keyword
(keyword_declaration) @keyword
(keyword_other) @keyword
(builtin_type) @type.builtin
(boolean) @boolean
(guillemet_string) @string
(octeti_string) @string
(backtick_string) @string
(ascii_string) @string
(string) @string
(number) @number
(identifier) @variable
(operator) @operator
(punctuation) @punctuation.bracket
(hash) @operator
