; Generated by scripta/generate_grammar.py — do not edit by hand.
; Faber syntax highlighting queries.

(frontmatter) @comment
(line_comment) @comment

(annotation) @attribute
(annotation
  (at_sign) @operator
  name: (annotation_name) @attribute)

(at_sign) @operator
(eq_sign) @operator
(comma_sign) @punctuation.delimiter
(lbrace) @punctuation.bracket
(rbrace) @punctuation.bracket

(annotation_name) @attribute
(known_annotation_name) @attribute

(annotation_modifier) @property

(annotation_field
  key: [(annotation_modifier) (identifier)] @property)

(annotation_field
  value: [(string) (ascii_string) (backtick_string) (guillemet_string) (octeti_string)] @string)

(annotation_field
  value: (identifier) @variable)

(annotation_field
  value: (annotation_value_type) @type.builtin)

(annotation_field
  value: (boolean) @boolean)

(annotation_field
  value: (number) @number)

(annotation_arguments
  (annotation_modifier) @property
  (string) @string
  (ascii_string) @string
  (backtick_string) @string
  (guillemet_string) @string
  (octeti_string) @string
  (identifier) @variable
  (annotation_value_type) @type.builtin
  (keyword_declaration) @keyword
  (keyword_other) @keyword
  (boolean) @boolean
  (number) @number)

(keyword_control) @keyword
(keyword_declaration) @keyword
(keyword_other) @keyword
(builtin_type) @type.builtin
(boolean) @boolean
(guillemet_string) @string
(octeti_string) @string
(backtick_string) @string
(ascii_string) @string
(string) @string
(number) @number
(identifier) @variable
(operator) @operator
(punctuation) @punctuation.bracket
(hash) @operator
